Repository jenkinsci/dark-theme-plugin, pull requests merged in 2020-05, with the labels that each got.

#7 Initialize README
  README.md
Labels: documentation

#8 Add a quick-start demo for the Dark Theme
  README.md
  demo/Dockerfile
  demo/Makefile
  demo/README.md
  demo/enable-theme.groovy
  demo/plugins.txt
Labels: documentation

#17 Improve README: screenshots and references
  README.md
  docs/images/screenshot_build_console.PNG
  docs/images/screenshot_main.png
Labels: documentation

#38 Deploy the demo to DockerHub
  demo/README.md
Labels: demo

#60 Upda the demo to the recent core build version
  demo/Dockerfile
Labels: demo

#66 Add release drafter, browser compat, use tags
  .github/workflows/release-drafter.yml
  README.md
Labels: chore, documentation

#67 Fix v2 header
  theme.css
Labels: bug

#70 Fix permissions for the exec file on DockerHub
  demo/Dockerfile
Labels: chore

#71 Revert "Demo - Add a link to the DockerHub badge"
  demo/README.md
Labels: skip-changelog

#72 Fix permissions in the demo launcher file
  demo/jenkins3.sh
Labels: chore

#74 Revert "Fix permissions for the exec file on DockerHub"
  demo/Dockerfile
Labels: skip-changelog

#62 Add support for local them development in the demo + Allow developing the dark login theme in the demo repo
  demo/Dockerfile
  demo/Makefile
  demo/README.md
  demo/enable-theme.groovy
  demo/jenkins3.sh
  demo/plugins.txt
  demo/static-file-server.yml
  docs/loginTheme.md
  theme.css
Labels: chore, squash-merge-me
