Repository jenkinsci/dark-theme-plugin, pull requests merged in 2020-07, with the labels that each got.

#115 Add .editorconfig
  .editorconfig
Labels: chore

#117 Theme text area handle
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#118 Improve contrast for dark link colours
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#116 Adapt table changes in core
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#121 Adjust alerts theming
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#122 Fix style flash with tab bar in new tables change
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: bug, skip-changelog

#124 Update big table header color
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: skip-changelog

#120 Bump minimum version to 2.248
  pom.xml
Labels: chore

#125 Fix tag template in release drafter configuration
  .github/release-drafter.yml
Labels: chore

#130 Include release drafter on tags
  .github/workflows/release-drafter.yml
Labels: chore

#131 Update minimum required version to 2.248 in README
  README.md
Labels: documentation

#132 Add more badges to README
  README.md
Labels: documentation
