Repository jenkinsci/dark-theme-plugin, pull requests merged in 2020-06, with the labels that each got.

#80 Update the demo to use Jenkins 2.239
  demo/Dockerfile
Labels: demo

#82 Add the changelog badge to README
  README.md
Labels: documentation

#90 Auto publish release on tag
  .github/workflows/release-drafter.yml
Labels: chore

#77 Convert to plugin
  .github/release-drafter.yml
  .gitignore
  .mvn/maven.config
  CONTRIBUTING.md
  Jenkinsfile
  README.md
  demo/Makefile
  demo/enable-theme.groovy
  pom.xml
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeRootAction.java
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
  src/main/resources/index.jelly
  src/main/resources/io/jenkins/plugins/darktheme/theme-system.css
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
  src/spotbugs/excludesFilter.xml
  src/test/java/io/jenkins/plugins/darktheme/jcasc/dark/DarkThemeJcascTest.java
  src/test/java/io/jenkins/plugins/darktheme/jcasc/darksystem/DarkSystemThemeJcascTest.java
  src/test/resources/io/jenkins/plugins/darktheme/jcasc/dark/ConfigurationAsCode.yml
  src/test/resources/io/jenkins/plugins/darktheme/jcasc/dark/ConfigurationAsCodeExport.yml
  src/test/resources/io/jenkins/plugins/darktheme/jcasc/darksystem/ConfigurationAsCode.yml
  src/test/resources/io/jenkins/plugins/darktheme/jcasc/darksystem/ConfigurationAsCodeExport.yml
Labels: enhancement

#92 Fix typo in release drafter config
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#93 Simplify release drafter config
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#94 Fix simple theme plugin URLs
  README.md
Labels: documentation

#96 Update the demo to use Jenkins 2.240 and recent plugins
  demo/Dockerfile
  demo/Makefile
  demo/enable-theme.groovy
  demo/jenkins3.sh
  demo/plugins.txt
Labels: demo

#106 Theme transparent buttons
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#107 Add active state for transparent buttons
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement

#109 Update manage variables for upcoming core
  src/main/resources/io/jenkins/plugins/darktheme/theme.css
Labels: enhancement
