Repository jenkinsci/dark-theme-plugin, pull requests merged in 2022-10, with the labels that each got.

#271 Removed now unneeded spotbugs filter
  src/spotbugs/excludesFilter.xml
Labels: chore

#274 Add backdrop variable for new Tippy tooltips
  src/main/frontend/main.scss
Labels: enhancement

#276 Update node to 18.x and npm to 9.x
  pom.xml
  renovate.json
Labels: dependencies

#281 Add dropdown colors
  src/main/frontend/main.scss
Labels: enhancement
