Repository jenkinsci/dark-theme-plugin, pull requests merged in 2023-12, with the labels that each got.

#431 Update JCasC usage in readme
  README.md
Labels: documentation

#433 Darker color for search, highlight search help icon on hover
  src/main/frontend/main.scss
Labels: enhancement

#434 Set card variables
  src/main/frontend/main.scss
Labels: enhancement

#439 Add Entra ID theme
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
Labels: enhancement

#440 Fix typo for system dark theme with entra id
  src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
Labels: bug
