Repository jenkinsci/dark-theme-plugin, pull requests merged in 2024-01, with the labels that each got.

#444 Require Jenkins 2.426.1 LTS or newer
  pom.xml
Labels: skip-changelog

#445 Update plugin manager description
  src/main/resources/index.jelly
Labels: enhancement

#446 Restrict header highlighting to search form
  src/main/frontend/main.scss
Labels: bug

#448 Update docs for using appearance page
  README.md
Labels: documentation
